/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppPendingRouteImport } from './routes/_app.pending'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppEventIdRouteImport } from './routes/_app.event.$id'
import { Route as AppPendingLiveRouteImport } from './routes/_app.pending_.live'
import { Route as AppProjectNameIndexRouteImport } from './routes/_app.project.$name.index'
import { Route as AppProjectNameTaskKeyRouteImport } from './routes/_app.project.$name.task.$key'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPendingRoute = AppPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppEventIdRoute = AppEventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPendingLiveRoute = AppPendingLiveRouteImport.update({
  id: '/pending_/live',
  path: '/pending/live',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectNameIndexRoute = AppProjectNameIndexRouteImport.update({
  id: '/project/$name/',
  path: '/project/$name/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectNameTaskKeyRoute = AppProjectNameTaskKeyRouteImport.update({
  id: '/project/$name/task/$key',
  path: '/project/$name/task/$key',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof AppPendingRoute
  '/settings': typeof AppSettingsRoute
  '/event/$id': typeof AppEventIdRoute
  '/pending/live': typeof AppPendingLiveRoute
  '/project/$name/': typeof AppProjectNameIndexRoute
  '/project/$name/task/$key': typeof AppProjectNameTaskKeyRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/pending': typeof AppPendingRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/event/$id': typeof AppEventIdRoute
  '/pending/live': typeof AppPendingLiveRoute
  '/project/$name': typeof AppProjectNameIndexRoute
  '/project/$name/task/$key': typeof AppProjectNameTaskKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/pending': typeof AppPendingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/event/$id': typeof AppEventIdRoute
  '/_app/pending_/live': typeof AppPendingLiveRoute
  '/_app/project/$name/': typeof AppProjectNameIndexRoute
  '/_app/project/$name/task/$key': typeof AppProjectNameTaskKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pending'
    | '/settings'
    | '/event/$id'
    | '/pending/live'
    | '/project/$name/'
    | '/project/$name/task/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/pending'
    | '/settings'
    | '/'
    | '/event/$id'
    | '/pending/live'
    | '/project/$name'
    | '/project/$name/task/$key'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/pending'
    | '/_app/settings'
    | '/_app/'
    | '/_app/event/$id'
    | '/_app/pending_/live'
    | '/_app/project/$name/'
    | '/_app/project/$name/task/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pending': {
      id: '/_app/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AppPendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/event/$id': {
      id: '/_app/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof AppEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pending_/live': {
      id: '/_app/pending_/live'
      path: '/pending/live'
      fullPath: '/pending/live'
      preLoaderRoute: typeof AppPendingLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/project/$name/': {
      id: '/_app/project/$name/'
      path: '/project/$name'
      fullPath: '/project/$name/'
      preLoaderRoute: typeof AppProjectNameIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/project/$name/task/$key': {
      id: '/_app/project/$name/task/$key'
      path: '/project/$name/task/$key'
      fullPath: '/project/$name/task/$key'
      preLoaderRoute: typeof AppProjectNameTaskKeyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppPendingRoute: typeof AppPendingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEventIdRoute: typeof AppEventIdRoute
  AppPendingLiveRoute: typeof AppPendingLiveRoute
  AppProjectNameIndexRoute: typeof AppProjectNameIndexRoute
  AppProjectNameTaskKeyRoute: typeof AppProjectNameTaskKeyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPendingRoute: AppPendingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppEventIdRoute: AppEventIdRoute,
  AppPendingLiveRoute: AppPendingLiveRoute,
  AppProjectNameIndexRoute: AppProjectNameIndexRoute,
  AppProjectNameTaskKeyRoute: AppProjectNameTaskKeyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
